baseURL: "https://blog.wmszhe.com/"
languageCode: "zh-CN"
title: "wmszhe"
theme: "PaperMod"
paginate: 10

hasCJKLanguage: true

params:
  # ä¸»é¢˜ ["auto", "light", "dark"]
  defaultTheme: auto
  # éšè—ä¸»é¢˜åˆ‡æ¢ icon
  disableThemeToggle: false
  ShowReadingTime: true
  # æ–‡ç« åº•éƒ¨æ˜¾ç¤ºåˆ†äº«
  ShowShareButtons: false
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowToc: true
  TocOpen: true

  homeInfoParams:
    Title: "Hello EveryOne ğŸ˜˜"
    Content: è·¯åœ¨è„šä¸‹ï¼Œå¿ƒå‘è¿œæ–¹

  profileMode:
    enabled: false

  cover:
    linkFullImages: true
  
  assets:
    favicon: assets/avatar.png

menu:
  main:
    - name: ğŸ”
      url: search/
      weight: 5
    - name: Archive
      url: archives
      weight: 10
    - name: Tags
      url: tags/
      weight: 15
    - name: About
      url: /about
      weight: 20
    - name: ç©Android
      url: https://www.wanandroid.com
      weight: 25
    - name: AndroidDevTools
      url: https://www.androiddevtools.cn/index.html
      weight: 30

# æœç´¢éœ€è¦çš„
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary