baseURL: "https://blog.110379.xyz/"
languageCode: "zh-CN"
title: "wmszhe"
theme: "PaperMod"

pagination:
  pagerSize: 10

hasCJKLanguage: true

minify:
  disableXML: true

markup:
  highlight:
    style: monokai
  goldmark:
    renderer:
      unsafe: true

params:
  # ä¸»é¢˜ ["auto", "light", "dark"]
  defaultTheme: auto
  # éšè—ä¸»é¢˜åˆ‡æ¢ icon
  disableThemeToggle: false
  ShowReadingTime: true
  # æ–‡ç« åº•éƒ¨æ˜¾ç¤ºåˆ†äº«
  ShowShareButtons: false
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowToc: true
  TocOpen: true

  homeInfoParams:
    Title: "Hello EveryOne ğŸ˜˜"
    Content: è·¯åœ¨è„šä¸‹ï¼Œå¿ƒå‘è¿œæ–¹

  profileMode:
    enabled: false

  cover:
    linkFullImages: true

  assets:
    favicon: avatar.png
    favicon16x16: avatar.png
    favicon32x32: avatar.png
    apple_touch_icon: avatar.png
    safari_pinned_tab: avatar.png

menu:
  main:
    - name: ğŸ”
      url: search/
      weight: 5
    - name: Archive
      url: archives
      weight: 10
    - name: Tags
      url: tags/
      weight: 15
    - name: About
      url: /about
      weight: 20
    - name: ç©Android
      url: https://www.wanandroid.com
      weight: 25
    - name: AndroidDevTools
      url: https://www.androiddevtools.cn/index.html
      weight: 30

outputFormats:
  llms:
    mediaType: "text/plain"
    baseName: "llms"
    isPlainText: true
    notAlternative: true

# æœç´¢éœ€è¦çš„
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - llms
